# Generated by Django 4.0.2 on 2022-03-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
                ('cc_myself', models.BooleanField()),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
    ]
