# Generated by Django 4.0.2 on 2022-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_dishes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': '获奖和荣誉', 'verbose_name_plural': '获奖和荣誉'},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='荣誉描述'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Award/', verbose_name='荣誉照片'),
        ),
    ]
