# Generated by Django 4.0.2 on 2022-03-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_dishes_options_alter_dishes_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='displays1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/displays1/')),
            ],
        ),
        migrations.CreateModel(
            name='displays2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=10, upload_to='media/displays2/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dishes',
            options={},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/dishies/'),
        ),
    ]
