# Generated by Django 4.0.2 on 2022-03-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_displays1_displays2_alter_dishes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='displays2',
            name='photo',
            field=models.ImageField(upload_to='media/displays2/'),
        ),
    ]
