# Generated by Django 4.0.2 on 2022-03-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_userinfo_alter_displays2_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='remarkTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('sex', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('remmark', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
