# Generated by Django 4.0.2 on 2022-03-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remarktables_delete_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remarktables',
            old_name='remmark',
            new_name='remark',
        ),
    ]
