# Generated by Django 4.0.2 on 2022-03-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='photo',
        ),
    ]
