# Generated by Django 4.0.2 on 2022-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_cart_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='historyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_dishes', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
