# Generated by Django 4.0.5 on 2022-12-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_historyorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarktables',
            name='email',
        ),
        migrations.RemoveField(
            model_name='remarktables',
            name='sex',
        ),
    ]
